#!/bin/sh
if ! (command -v emacsclient > /dev/null); then
    echo 'emacsclient not found'
    exit
fi

if [ "$1" == "-" ]; then
    # read from STDIN
    TMP="$(mktemp /tmp/stdin-XXX)"
    cat > $TMP
    emacsclient -n $TMP
    rm $TMP
else
    # open file or current directory
    if [ $# -eq 0 ]; then
        emacsclient -n .
    else
        emacsclient -n "$@"
    fi
fi
