#!/bin/sh
if [ -n "$TMUX" ]; then
    local_command='tmux rename-window $(echo "%r@%n(%h:%p)")'
    command -p ssh -o PermitLocalCommand=yes -o LocalCommand="${local_command}" "$@"
    tmux set-window-option -u automatic-rename
else
    command -p ssh "$@"
fi
