#!/bin/sh
if [ -n "$TMUX" ]; then
    original_window_name=$(tmux display -p '#{window_name}')
    local_command='tmux rename-window $(echo "%r@%n(%h:%p)")'
fi

command -p ssh -o PermitLocalCommand=yes -o LocalCommand="${local_command}" "$@"

if [ -n "$original_window_name" ]; then
    tmux rename-window $original_window_name
fi
