#!/bin/sh
if [ "$(uname)" != "Darwin" ]; then
    exit 1
fi

export SCRIPT=$(cat <<'EOT'
on run argv
  tell application "System Events"
    try
      tell application process "Stickies"
        set names to name of every window
        repeat with name in names
          set value of text area 1 of scroll area 1 of window name to item 1 of argv
        end repeat
      end tell
    end try
  end tell
end run
EOT
)
osascript -e "$SCRIPT" "$1"
