(defun my-dired-mode-hook ()
  (define-key dired-mode-map (kbd "o")   'dired-display-file)
  (define-key dired-mode-map (kbd "r")   'wdired-change-to-wdired-mode)
  (define-key dired-mode-map (kbd "C-o") 'other-window)
  (define-key dired-mode-map (kbd "C-s") 'dired-isearch-filenames))
(add-hook 'dired-mode-hook 'my-dired-mode-hook)
